# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: File.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'rpc/File.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nFile.proto\"?\n\tFileChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\"f\n\rFileDataReply\x12\x0e\n\x06oss_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x15\n\roriginal_name\x18\x04 \x01(\t\x12\x13\n\x0b\x66ile_suffix\x18\x05 \x01(\t\"-\n\x0b\x46ileRequest\x12\x1e\n\nfile_chunk\x18\x01 \x01(\x0b\x32\n.FileChunk\"H\n\tFileReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1c\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x0e.FileDataReply22\n\x04\x46ile\x12*\n\nUploadFile\x12\x0c.FileRequest\x1a\n.FileReply\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'File_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=14
  _globals['_FILECHUNK']._serialized_end=77
  _globals['_FILEDATAREPLY']._serialized_start=79
  _globals['_FILEDATAREPLY']._serialized_end=181
  _globals['_FILEREQUEST']._serialized_start=183
  _globals['_FILEREQUEST']._serialized_end=228
  _globals['_FILEREPLY']._serialized_start=230
  _globals['_FILEREPLY']._serialized_end=302
  _globals['_FILE']._serialized_start=304
  _globals['_FILE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
