# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import Pulsar_pb2 as Pulsar__pb2

GRPC_GENERATED_VERSION = '1.72.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Pulsar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PulsarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PulsarMatcher = channel.unary_unary(
                '/Pulsar/PulsarMatcher',
                request_serializer=Pulsar__pb2.PulsarMatcherRequestList.SerializeToString,
                response_deserializer=Pulsar__pb2.PulsarReply.FromString,
                _registered_method=True)
        self.PulsarScores = channel.unary_unary(
                '/Pulsar/PulsarScores',
                request_serializer=Pulsar__pb2.PulsarScoresRequestList.SerializeToString,
                response_deserializer=Pulsar__pb2.PulsarReply.FromString,
                _registered_method=True)


class PulsarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PulsarMatcher(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PulsarScores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PulsarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PulsarMatcher': grpc.unary_unary_rpc_method_handler(
                    servicer.PulsarMatcher,
                    request_deserializer=Pulsar__pb2.PulsarMatcherRequestList.FromString,
                    response_serializer=Pulsar__pb2.PulsarReply.SerializeToString,
            ),
            'PulsarScores': grpc.unary_unary_rpc_method_handler(
                    servicer.PulsarScores,
                    request_deserializer=Pulsar__pb2.PulsarScoresRequestList.FromString,
                    response_serializer=Pulsar__pb2.PulsarReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Pulsar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Pulsar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pulsar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PulsarMatcher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Pulsar/PulsarMatcher',
            Pulsar__pb2.PulsarMatcherRequestList.SerializeToString,
            Pulsar__pb2.PulsarReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PulsarScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Pulsar/PulsarScores',
            Pulsar__pb2.PulsarScoresRequestList.SerializeToString,
            Pulsar__pb2.PulsarReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
