# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Pulsar.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'rpc/Pulsar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cPulsar.proto\"A\n\x18PulsarMatcherRequestList\x12%\n\x06pulsar\x18\x01 \x03(\x0b\x32\x15.PulsarMatcherRequest\"?\n\x17PulsarScoresRequestList\x12$\n\x06pulsar\x18\x01 \x03(\x0b\x32\x14.PulsarScoresRequest\"\x8b\x02\n\x14PulsarMatcherRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06period\x18\x04 \x01(\t\x12\x1a\n\x12\x64ispersion_measure\x18\x05 \x01(\t\x12\x0e\n\x06ra_deg\x18\x06 \x01(\t\x12\x0f\n\x07\x64\x65\x63_deg\x18\x07 \x01(\t\x12\x1a\n\x12galactic_longitude\x18\x08 \x01(\x01\x12\x19\n\x11galactic_latitude\x18\t \x01(\x01\x12\x16\n\x0eprofiles_shape\x18\n \x01(\t\x12\x16\n\x0e\x66olding_period\x18\x0b \x01(\x01\x12\x12\n\ndiscoverer\x18\x0c \x01(\t\"\\\n\x13PulsarScoresRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x10\n\x08\x66ile_url\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x01\",\n\x0bPulsarReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2~\n\x06Pulsar\x12:\n\rPulsarMatcher\x12\x19.PulsarMatcherRequestList\x1a\x0c.PulsarReply\"\x00\x12\x38\n\x0cPulsarScores\x12\x18.PulsarScoresRequestList\x1a\x0c.PulsarReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Pulsar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PULSARMATCHERREQUESTLIST']._serialized_start=16
  _globals['_PULSARMATCHERREQUESTLIST']._serialized_end=81
  _globals['_PULSARSCORESREQUESTLIST']._serialized_start=83
  _globals['_PULSARSCORESREQUESTLIST']._serialized_end=146
  _globals['_PULSARMATCHERREQUEST']._serialized_start=149
  _globals['_PULSARMATCHERREQUEST']._serialized_end=416
  _globals['_PULSARSCORESREQUEST']._serialized_start=418
  _globals['_PULSARSCORESREQUEST']._serialized_end=510
  _globals['_PULSARREPLY']._serialized_start=512
  _globals['_PULSARREPLY']._serialized_end=556
  _globals['_PULSAR']._serialized_start=558
  _globals['_PULSAR']._serialized_end=684
# @@protoc_insertion_point(module_scope)
